org.gradle.caching=true
org.gradle.configuration-cache=true
systemProp.nebula.features.coreLockingSupport=true
nebula.integTest=false
org.gradle.jvmargs=-Xmx1g "-XX:MaxMetaspaceSize=512m"
# Disable Kotlin FUS (Feature Usage Statistics) to fix configuration cache issue
# See: https://youtrack.jetbrains.com/issue/KT-69078/Gradle-Add-option-to-disable-FUS-Service
kotlin.internal.collectFUSMetrics=false
kotlin.stdlib.default.dependency=false
